# Exercise 1

In [63]:
import numpy as np

In [64]:
#a. Create a null vector of size 10 but the fifth value which is 1
null_v = np.zeros(10)
null_v[4] = 1

In [65]:
#b. Create a vector with values ranging from 10 to 49
range_v = np.arange(10,49)


In [66]:
#c. Reverse a vector (first element becomes last)
reverse= range_v[::-1]

In [67]:
#d. Create a 3x3 matrix with values ranging from 0 to 8
M = np.arange(0,9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [68]:
#e. Find indices of non-zero elements from [1,2,0,0,4,0]
i = np.where(np.array([1,2,0,0,4,0]) != 0)
print(i)

(array([0, 1, 4]),)


In [69]:
#f. Create a random vector of size 30 and find the mean value
mean = np.mean(np.random.random(30))

In [70]:
#g. Create a 2d array with 1 on the border and 0 inside
dim = 7

B = np.zeros((dim,dim), int)
B[::dim-1,:] = 1
B[:,::dim-1] = 1

print(B)


[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [71]:
#h. Create a 8x8 matrix and fill it with a checkerboard pattern
c = np.ones((8,8), int)

c[1::2,::2] = 0
c[::2,1::2] = 0

print(c)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [72]:
#i. Create a checkerboard 8x8 matrix using the tile function
matrix = np.diag((1,1))
c2 = np.tile(matrix,(4,4))
print(c2)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [75]:
#j. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[3:9] = -Z[3:9]
print(Z)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [76]:
#k. Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.06595449 0.22319372 0.43363795 0.52194564 0.58572346 0.7110077
 0.74906299 0.78147625 0.85882621 0.92435973]


In [77]:
#l. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


In [78]:
#m. How to convert an integer (32 bits) array into a float (32 bits) in place?''
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = np.float32(Z)
print(Z.dtype)

int32
float32


In [79]:
#n. How to get the diagonal of a dot product?
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diagonal(C)
print(D)

[ 18  66 132]


# Exercise 2

In [91]:
#I used the same code for solving exercise 2 from yesterday, therefore I defined some functions in the next cell 
#to solve day2 exercise without numpy

N = 250 

X = np.random.randint(100, size = (N,N))
Y = np.random.randint(100, size = (N,N+1))
Z = np.dot(X,Y)
    
result = Z.tolist()

for r in result:
    print(r)

[608917, 558008, 560929, 534044, 572215, 616678, 592224, 599813, 567626, 593393, 581162, 580330, 568254, 529522, 586678, 584166, 586234, 574786, 617302, 569808, 603915, 621946, 561292, 570281, 584190, 601093, 572661, 587099, 565509, 550801, 610538, 605787, 562218, 552932, 541120, 600174, 550945, 583419, 609565, 576922, 606332, 589333, 601731, 585690, 572826, 557318, 584633, 613167, 571277, 578418, 596935, 578010, 560342, 555746, 599779, 634420, 604594, 603440, 563417, 582997, 557172, 553078, 602021, 556910, 584855, 611267, 556242, 581031, 602453, 597201, 575848, 561505, 548369, 576055, 618025, 618325, 593895, 535438, 616144, 614613, 627925, 587319, 576191, 593445, 590442, 622992, 575063, 604443, 613945, 573472, 630829, 567390, 595618, 582704, 589554, 556634, 650851, 589370, 597151, 572842, 542712, 602120, 611686, 583914, 653497, 603167, 596031, 541028, 563777, 604137, 572060, 600009, 540751, 571382, 611165, 552003, 578803, 626194, 577241, 573213, 571031, 641529, 579604, 567951, 603286,

In [92]:
import random

def matrix_nn(N):
    X =  [[random.randint(0, 100) for i in range(N)] for j in range(N)]
    return X

def matrix_nm(N):
    Y = [[random.randint(0, 100) for i in range(N+1)] for j in range(N)]
    return Y

def matrix_dot(X,Y):
    Z = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return Z

def printm(Z):
    for r in Z:
        print(r)

def run(n = 250):
    X= matrix_nn(N)
    Y= matrix_nm(N)
    Z= matrix_dot(X,Y)
    printm(Z)

run(N)

[610492, 614215, 638061, 565563, 647482, 583481, 604574, 580018, 611423, 633763, 667370, 638794, 595332, 607450, 597973, 593639, 629079, 618101, 585710, 649156, 578554, 637988, 587367, 593872, 594934, 612777, 607432, 619493, 573738, 646537, 619892, 613072, 573072, 646192, 580027, 630351, 568740, 654452, 655750, 554257, 571478, 635762, 602694, 598857, 596911, 587739, 617385, 600018, 583415, 607327, 603742, 619461, 598989, 645382, 626434, 593655, 612219, 579142, 627613, 582949, 564301, 624851, 598383, 585968, 594733, 662998, 613364, 580622, 632088, 637712, 574140, 623519, 604087, 617914, 608706, 607191, 625543, 591246, 545633, 618337, 583747, 653178, 645041, 661601, 651389, 597703, 646992, 574311, 587532, 634972, 635144, 633048, 593649, 586009, 653750, 650362, 641118, 644675, 593124, 636085, 619249, 646599, 624178, 605465, 622075, 643269, 585541, 630117, 641280, 612227, 613682, 609180, 641977, 576509, 647380, 538962, 620439, 601461, 588367, 562376, 588688, 647464, 592575, 631101, 589979,

# Exercise 3

In [99]:
#a. Create a "Person" class which takes firstname and lastname as arguments to the constructor (___init___) 
#and define a method that returns the full name of the person as a combined string.
from classroom import Person, Student,Teacher 

randomguy = Person('Generic', 'Name')
name = randomguy.whatsyourname()
print(name)

#b. Create a "Student" class which inherits from the "Person" class, takes the subject area as an additional argument to the constructor 
#and define a method that prints the full name and the subject area of the student.

#c. You should be able now to use your "Student" class like this:

me = Student('Alfredo', 'Bellisario', 'PhDysics') 
me.whatsyourstudent()

#d. Create a "Teacher" class which also inherits from "Person", takes the name of the course (e.g. Python programming) as an argument 
#and define a method that prints the full name of the teacher and the course he teaches.

teacher = Teacher('Filipe', 'Maia', 'Pythonology and more snakes')
teacher.whatsyourprof()

Generic Name
Alfredo Bellisario, PhDysics
Filipe Maia, Pythonology and more snakes
